name: codemagic_manager
description: Package allowing to query and manage Codemagic builds
version: 0.1.0
homepage: https://roszkowski.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  freezed_annotation: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: ^0.10.9
  json_serializable: ^3.3.0

flutter:
